[package]
name = "m3u_cleaner"
version = "0.1.0"
edition = "2021"
build = "build.rs"  # Ajouter cette ligne

[dependencies]
regex = "1.5"
egui = "0.20"
eframe = "0.20"
rfd = "0.12"
image = "0.24"

[profile.release]
panic = "abort"

[[bin]]
name = "m3u_cleaner"
path = "src/main.rs"
